# Lecture 8

In [2]:
import numpy as np
N=np.array([0,1,2,3,4,3,4,3])
N.reshape((4,2))
print(N)
print(N.base)
print(N)

[0 1 2 3 4 3 4 3]
None
[0 1 2 3 4 3 4 3]


In [11]:
def f(i,j):
    return i+j
ca=np.fromfunction(f,(3,3))
print(ca)
ca=np.fromfunction(lambda i,j: i+j, (3,3))
print(ca)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [17]:
ca[1][2]#don't use it
ca[1,2]#usa questo
x=np.zeros((3,3))
x[0]=np.array([5,4,3])
print(x)
print(x[:2])


[[5. 4. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 4. 3.]
 [0. 0. 0.]]


In [24]:
ca[0,0::2]


array([0., 2.])

In [25]:
x=np.array([1,2,3,4])
x[np.newaxis,:]


array([[1, 2, 3, 4]])

In [42]:
class Porco():
    me=0
    def __init__(self,pippolacoca=0):
        self.me=pippolacoca
x=Porco()
x=Porco(2)
print(x.me)


2


In [62]:
#np.random.seed(3)


[ 0 21 15]
6


In [ ]:
a.sum(axis=0)#along la prima colonna
a.sum(axis=1)#riga


In [6]:
b=np.array((2,3,4,5))


In [15]:
a=np.array([2,3,4,5,6])+1
a
a=a%2
a
a+np.array([1])
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
a+b#somma a tutto il vettore questo altro vettore
a=np.arange(6)
print(a)
b=np.arange(0,60,10)
print(b)
T=b[:,np.newaxis]+a[np.newaxis,:]#guarda un po' le dimensioni (6,1)+(1,6) lo fa zio pera
print(T)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [1]:
#prime due domande su python, non difficoltà di computazione 6+6 punti
#sull understanding della lingua 7 points programming on sequences
# 7 points between programming and knowledge of the language
#use numpy 7, you can't use standard python featurs
A=[10,20,30]
X=A
def f():
    A=10
    x= A
    

SyntaxError: name 'A' is assigned to before global declaration (3545741148.py, line 7)